# Generated by Django 5.0.7 on 2024-07-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_imagen'),
        ('tienda', '0004_alter_producto_imagen'),
    ]

    operations = [
    ]
